Repository NIPA-OpenUP/oss-governance-guide, pull requests merged in 2021-04, with the labels that each got.

#80 SW -> 소프트웨어
  oss-governance-guide.md
Labels: 범위: 공통, 타입: 수정

#81 add readme
  README.md
Labels: 범위: 공통

#82 add link to create a issue
  README.md
Labels: 범위: 공통, 타입: 수정

#83 비교적 사소한 문구 수정들.
  oss-governance-guide.md
Labels: 범위: 공통, 타입: 리뷰

#86 문구 수정 및 일부 내용 추가
  oss-governance-guide.md
Labels: 범위: 공통, 타입: 리뷰, 타입: 추가

#90 add ISO intro
  oss-governance-guide.md
Labels: 범위: 사용하기, 타입: 수정

#91 주요 오픈소스 관리 도구 추가
  assets/logo-blackduck.png
  assets/logo-codeeye.png
  assets/logo-fossid.png
  assets/logo-insignary.png
  assets/logo-labrador.png
  oss-governance-guide.md
Labels: 범위: 사용하기, 타입: 수정

#93 Git lectures 추가
  oss-governance-guide.md
Labels: 범위: 기여하기, 타입: 추가

#88 update toc level
  assets/logo-blackduck.png
  assets/logo-codeeye.png
  assets/logo-fossid.png
  assets/logo-insignary.png
  assets/logo-labrador.png
  oss-governance-guide.md
Labels: 범위: 공통, 타입: 수정

#98 OSPO 기업 사례 추가
  README.md
  content/en/intro/_index.md
  content/en/ospo/_index.md
Labels: 범위: OSPO, 타입: 추가

#102 add changes on markdown file
  content/en/contributing/_index.md
  content/en/ospo/_index.md
  content/en/releasing/_index.md
  content/en/using/_index.md
Labels: 범위: 공통, 타입: 수정
